# http://localhost:8080/actuator/gateway/routes
server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: userms
          uri: lb://USERMS
          predicates:
            - Path=/dummy-userms/**
          filters:
            - RewritePath=/dummy-userms/(?<path>.*), /$\{path}

        - id: orderms
          uri: lb://ORDERMS
          predicates:
            - Path=/dummy-orderms/**
          filters:
            - RewritePath=/dummy-orderms/(?<path>.*), /$\{path}

# http://localhost:8080/actuator/gateway/routes
management:
  endpoints:
    web:
      exposure:
        include: '*'